// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QLNH.DAL;

#nullable disable

namespace QLNH.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260502073639_AddCustomSqlObjects")]
    partial class AddCustomSqlObjects
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QLNH.Models.Banan", b =>
                {
                    b.Property<int>("SoBan")
                        .HasColumnType("int");

                    b.Property<int?>("SoGhe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(4);

                    b.Property<int?>("Tang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Trong");

                    b.HasKey("SoBan")
                        .HasName("PK__banan__21B4EECABCF55A8E");

                    b.ToTable("banan", (string)null);
                });

            modelBuilder.Entity("QLNH.Models.Chitiethoadon", b =>
                {
                    b.Property<int>("MaChiTiet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChiTiet"));

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(10, 0)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("MaHoaDon")
                        .HasColumnType("int");

                    b.Property<int?>("MaMon")
                        .HasColumnType("int");

                    b.Property<int?>("SoLuong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<DateTime?>("ThoiGianGoi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("TrangThaiMon")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("ChoCheBien");

                    b.HasKey("MaChiTiet")
                        .HasName("PK__chitieth__CDF0A1148E922BDD");

                    b.HasIndex("MaHoaDon");

                    b.HasIndex("MaMon");

                    b.ToTable("chitiethoadon", (string)null);
                });

            modelBuilder.Entity("QLNH.Models.Chitietphieugoi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<int?>("MaMon")
                        .HasColumnType("int");

                    b.Property<int?>("MaPhieu")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("ChoCheBien");

                    b.HasKey("Id")
                        .HasName("PK__chitietp__3214EC2753C6480D");

                    b.HasIndex("MaMon");

                    b.HasIndex("MaPhieu");

                    b.ToTable("chitietphieugoi", (string)null);
                });

            modelBuilder.Entity("QLNH.Models.GopYKhachHang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("NgayGopY")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDungGopY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoSaoDanhGia")
                        .HasColumnType("int");

                    b.Property<string>("TenKhachHang")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GopYKhachHangs");
                });

            modelBuilder.Entity("QLNH.Models.Hoadon", b =>
                {
                    b.Property<int>("MaHoaDon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHoaDon"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal?>("GiamGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10, 0)")
                        .HasDefaultValue(0m);

                    b.Property<int?>("MaNvPhucVu")
                        .HasColumnType("int")
                        .HasColumnName("MaNV_PhucVu");

                    b.Property<int?>("SoBan")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ThoiGianRa")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("ThoiGianVao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal?>("TienKhachDua")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10, 0)")
                        .HasDefaultValue(0m);

                    b.Property<decimal?>("TienThua")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10, 0)")
                        .HasDefaultValue(0m);

                    b.Property<decimal?>("TongThanhToan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10, 0)")
                        .HasDefaultValue(0m);

                    b.Property<decimal?>("TongTienHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10, 0)")
                        .HasDefaultValue(0m);

                    b.Property<string>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("ChuaThanhToan");

                    b.Property<decimal?>("Vat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10, 0)")
                        .HasDefaultValue(0m)
                        .HasColumnName("VAT");

                    b.HasKey("MaHoaDon")
                        .HasName("PK__hoadon__835ED13BA9339D9B");

                    b.HasIndex("MaNvPhucVu");

                    b.HasIndex("SoBan");

                    b.ToTable("hoadon", (string)null);
                });

            modelBuilder.Entity("QLNH.Models.Monan", b =>
                {
                    b.Property<int>("MaMon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaMon"));

                    b.Property<bool?>("DangKinhDoanh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("DonVi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("GiaTien")
                        .HasColumnType("decimal(10, 0)");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("MaNhom")
                        .HasColumnType("int");

                    b.Property<string>("TenMon")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaMon")
                        .HasName("PK__monan__3A5B29A892498510");

                    b.HasIndex("MaNhom");

                    b.ToTable("monan", (string)null);
                });

            modelBuilder.Entity("QLNH.Models.Nhanvien", b =>
                {
                    b.Property<int>("MaNv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaNV");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNv"));

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaNv")
                        .HasName("PK__nhanvien__2725D70A2239DDA3");

                    b.HasIndex(new[] { "TenDangNhap" }, "UQ__nhanvien__55F68FC030D9FD10")
                        .IsUnique();

                    b.ToTable("nhanvien", (string)null);
                });

            modelBuilder.Entity("QLNH.Models.Nhommon", b =>
                {
                    b.Property<int>("MaNhom")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNhom"));

                    b.Property<string>("TenNhom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaNhom")
                        .HasName("PK__nhommon__234F91CD680A5E30");

                    b.ToTable("nhommon", (string)null);
                });

            modelBuilder.Entity("QLNH.Models.Phieugoi", b =>
                {
                    b.Property<int>("MaPhieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhieu"));

                    b.Property<int?>("MaHoaDon")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ThoiGianTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("MaPhieu")
                        .HasName("PK__phieugoi__2660BFE078CFFCF0");

                    b.HasIndex("MaHoaDon");

                    b.ToTable("phieugoi", (string)null);
                });

            modelBuilder.Entity("QLNH.Models.Thongbao", b =>
                {
                    b.Property<int>("MaTb")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaTB");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTb"));

                    b.Property<bool?>("DaXem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("ThoiGian")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("MaTb")
                        .HasName("PK__thongbao__2725006F892C146F");

                    b.ToTable("thongbao", (string)null);
                });

            modelBuilder.Entity("QLNH.Models.Chitiethoadon", b =>
                {
                    b.HasOne("QLNH.Models.Hoadon", "MaHoaDonNavigation")
                        .WithMany("Chitiethoadons")
                        .HasForeignKey("MaHoaDon")
                        .HasConstraintName("FK__chitietho__MaHoa__5535A963");

                    b.HasOne("QLNH.Models.Monan", "MaMonNavigation")
                        .WithMany("Chitiethoadons")
                        .HasForeignKey("MaMon")
                        .HasConstraintName("FK__chitietho__MaMon__5629CD9C");

                    b.Navigation("MaHoaDonNavigation");

                    b.Navigation("MaMonNavigation");
                });

            modelBuilder.Entity("QLNH.Models.Chitietphieugoi", b =>
                {
                    b.HasOne("QLNH.Models.Monan", "MaMonNavigation")
                        .WithMany("Chitietphieugois")
                        .HasForeignKey("MaMon")
                        .HasConstraintName("FK__chitietph__MaMon__60A75C0F");

                    b.HasOne("QLNH.Models.Phieugoi", "MaPhieuNavigation")
                        .WithMany("Chitietphieugois")
                        .HasForeignKey("MaPhieu")
                        .HasConstraintName("FK__chitietph__MaPhi__5FB337D6");

                    b.Navigation("MaMonNavigation");

                    b.Navigation("MaPhieuNavigation");
                });

            modelBuilder.Entity("QLNH.Models.Hoadon", b =>
                {
                    b.HasOne("QLNH.Models.Nhanvien", "MaNvPhucVuNavigation")
                        .WithMany("Hoadons")
                        .HasForeignKey("MaNvPhucVu")
                        .HasConstraintName("FK__hoadon__MaNV_Phu__4AB81AF0");

                    b.HasOne("QLNH.Models.Banan", "SoBanNavigation")
                        .WithMany("Hoadons")
                        .HasForeignKey("SoBan")
                        .HasConstraintName("FK__hoadon__SoBan__49C3F6B7");

                    b.Navigation("MaNvPhucVuNavigation");

                    b.Navigation("SoBanNavigation");
                });

            modelBuilder.Entity("QLNH.Models.Monan", b =>
                {
                    b.HasOne("QLNH.Models.Nhommon", "MaNhomNavigation")
                        .WithMany("Monans")
                        .HasForeignKey("MaNhom")
                        .HasConstraintName("FK__monan__MaNhom__45F365D3");

                    b.Navigation("MaNhomNavigation");
                });

            modelBuilder.Entity("QLNH.Models.Phieugoi", b =>
                {
                    b.HasOne("QLNH.Models.Hoadon", "MaHoaDonNavigation")
                        .WithMany("Phieugois")
                        .HasForeignKey("MaHoaDon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__phieugoi__MaHoaD__5BE2A6F2");

                    b.Navigation("MaHoaDonNavigation");
                });

            modelBuilder.Entity("QLNH.Models.Banan", b =>
                {
                    b.Navigation("Hoadons");
                });

            modelBuilder.Entity("QLNH.Models.Hoadon", b =>
                {
                    b.Navigation("Chitiethoadons");

                    b.Navigation("Phieugois");
                });

            modelBuilder.Entity("QLNH.Models.Monan", b =>
                {
                    b.Navigation("Chitiethoadons");

                    b.Navigation("Chitietphieugois");
                });

            modelBuilder.Entity("QLNH.Models.Nhanvien", b =>
                {
                    b.Navigation("Hoadons");
                });

            modelBuilder.Entity("QLNH.Models.Nhommon", b =>
                {
                    b.Navigation("Monans");
                });

            modelBuilder.Entity("QLNH.Models.Phieugoi", b =>
                {
                    b.Navigation("Chitietphieugois");
                });
#pragma warning restore 612, 618
        }
    }
}
